### ISSUE TITLE
Failed to find Premain-Class manifest attribute in G:\WhisperSystems\PushServer\Push-Server-0.12.0-capsule-fat.jar Error occurred during initialization of VM agent library failed to init: instrument

### ISSUE THREAD

**Issue by reykjavik11** [WhisperSystems/PushServer#7]
I have some problem while start  Push-Server-0.12.0-capsule-fat.jar 
It' s next message:

CAPSULE: Waiting for client to connect...
Failed to find Premain-Class manifest attribute in G:\freelance\WhisperSystems\PushServer\Push-Server-0.12.0-capsule-fat.jar
Error occurred during initialization of VM
agent library failed to init: instrument
CAPSULE: Client connection failed.
CAPSULE EXCEPTION: Accept timed out while processing null null: null
java.net.SocketTimeoutException: Accept timed out
        at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
        at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
        at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
        at java.net.PlainSocketImpl.accept(Unknown Source)
        at java.net.ServerSocket.implAccept(Unknown Source)
        at java.net.ServerSocket.accept(Unknown Source)
        at Capsule.startServer(Capsule.java:1717)
        at Capsule.launch0(Capsule.java:1378)
        at Capsule.launch(Capsule.java:1351)
        at Capsule.launch(Capsule.java:1280)
        at Capsule.main0(Capsule.java:399)
        at Capsule.main(Capsule.java:379)
CAPSULE: Closing comm
CAPSULE: Cleanup 

Any idea?
Thanks

**Comment by moxie0** [comment]
thanks but this is an issue tracker not a discussion forum
